### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [yuhi20bc/prj-rev-bwfs-tea-cozy#6]
**Grade:** Needs Improvement

**Summary:** This project has a lot of good work in it! Overall the basics of the project are nicely covered, but without styles or images working (without me fixing it) the site is essentially naked. So, make sure to use relative links and not absolute links (css/image links). Also, review your HTML for indentation consistency and try to keep it as clean as possible! Fixing these issues will quickly make this project great!

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline- block.html.

Good luck!

**Comment by griffinlacek** [comment]
Sorry about this. Wrong repo.

**Comment by Ealexprice** [comment]
what do you mean wrong repo?  I'm confused. What does my website being naked mean? I use inline block and flex for my horizontal.... at least I thought so.  Plus the links you put do not work.

**Comment by griffinlacek** [comment]
This comment was meant for another project. Thus the "wrong repo" comment. It has no bearing on your project and your summary is issue #5. Sorry for the confusion! Please disregard the entire Summary here and only focus on #5.
